data_dir: dataset/fabrics_split
results_path: results/efficientnetv2
save_path: models/efficientnetv2/efficientnetv2.pt

batch_size: 32
num_epochs: 50
image_size: 224
learning_rate: 0.0003
num_workers: 2

loss_function: focal
pretrained: true
