model_name: resnet50
pretrained: true
num_epochs: 50            # αυξήσαμε τις εποχές
batch_size: 32
learning_rate: 0.0001
loss_function: focal
image_size: 224
num_workers: 0
save_path: models/resnet50/resnet50_50ep.pt
results_path: results/resnet50_50ep/
data_dir: dataset/fabrics_split
