model_name: vit_b_16
pretrained: true
num_epochs: 50
batch_size: 32
learning_rate: 0.0001
loss_function: focal
image_size: 224
num_workers: 0
save_path: models/vit/vit.pt
results_path: results/vit/
data_dir: dataset/fabrics_split
